// Class: ReadCuts
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::Cuts
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : mdunser
Date           : Thu Jun 13 11:39:05 2013
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/mdunser/finalRA5/CMSSW_5_3_7_patch5/src/DiLeptonAnalysis/NTupleProducer/macros/dps/tmvaStuff
Training events: 9970
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
    CutRangeMin[4]: "-1.000000e+00"
    CutRangeMin[5]: "-1.000000e+00"
    CutRangeMin[6]: "-1.000000e+00"
    CutRangeMin[7]: "-1.000000e+00"
    CutRangeMin[8]: "-1.000000e+00"
    CutRangeMin[9]: "-1.000000e+00"
    CutRangeMin[10]: "-1.000000e+00"
    CutRangeMin[11]: "-1.000000e+00"
    CutRangeMin[12]: "-1.000000e+00"
    CutRangeMin[13]: "-1.000000e+00"
    CutRangeMin[14]: "-1.000000e+00"
    CutRangeMin[15]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
    CutRangeMax[4]: "-1.000000e+00"
    CutRangeMax[5]: "-1.000000e+00"
    CutRangeMax[6]: "-1.000000e+00"
    CutRangeMax[7]: "-1.000000e+00"
    CutRangeMax[8]: "-1.000000e+00"
    CutRangeMax[9]: "-1.000000e+00"
    CutRangeMax[10]: "-1.000000e+00"
    CutRangeMax[11]: "-1.000000e+00"
    CutRangeMax[12]: "-1.000000e+00"
    CutRangeMax[13]: "-1.000000e+00"
    CutRangeMax[14]: "-1.000000e+00"
    CutRangeMax[15]: "-1.000000e+00"
VarProp[0]: "FMin" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FMin"
    VarProp[4]: "FMin"
    VarProp[5]: "FMax"
    VarProp[6]: "FSmart"
    VarProp[7]: "FMin"
    VarProp[8]: "FSmart"
    VarProp[9]: "FMin"
    VarProp[10]: "FMin"
    VarProp[11]: "FSmart"
    VarProp[12]: "FMax"
    VarProp[13]: "FMin"
    VarProp[14]: "FMin"
    VarProp[15]: "FMin"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
HT                            HT                            HT                            H_{T}                         GeV                               'F'    [0,1997.75524902]
pT1                           pT1                           pT1                           p_{T}^{1}                     GeV                               'F'    [20.0015449524,450.972290039]
pT2                           pT2                           pT2                           p_{T}^{2}                     GeV                               'F'    [10.0143241882,228.861190796]
NJ                            NJ                            NJ                            N Jets                                                          'I'    [0,7]
Mll                           Mll                           Mll                           Inv. mass of leptons                                            'F'    [8.01255989075,972.719665527]
MT1                           MT1                           MT1                           m_{T}^{leading}                                                 'F'    [10.3086061478,929.568359375]
MET                           MET                           MET                           E_{T}^{miss}                                                    'F'    [3.95599842072,521.006225586]
Jet0Pt                        Jet0Pt                        Jet0Pt                        jet-p_{T}^{0}                                                   'F'    [-0,1068.73571777]
eta1                          eta1                          eta1                          #eta_{leading}                                                  'F'    [-2.39974975586,2.39961290359]
NbJ                           NbJ                           NbJ                           #N_{b-jets}^{loose}                                             'I'    [0,4]
NbJmed                        NbJmed                        NbJmed                        #N_{b-jets}^{medium}                                            'I'    [0,3]
MT2                           MT2                           MT2                           #M_{T2}                                                         'F'    [0,192.143051147]
dPhiMLs                       dPhiMLs                       dPhiMLs                       #dPhiMLs                                                        'I'    [1.3684476614,3.14158463478]
NMus                          NMus                          NMus                          #NMus                                                           'F'    [2,4]
PFIso1                        PFIso1                        PFIso1                        #iso1                                                           'F'    [0,0.0999513044953]
PFIso2                        PFIso2                        PFIso2                        #iso2                                                           'F'    [0,0.0999603047967]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCuts : public IClassifierReader {

 public:

   // constructor
   ReadCuts( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCuts" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HT", "pT1", "pT2", "NJ", "Mll", "MT1", "MET", "Jet0Pt", "eta1", "NbJ", "NbJmed", "MT2", "dPhiMLs", "NMus", "PFIso1", "PFIso2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 1997.75524902344;
      fVmin[1] = 20.0015449523926;
      fVmax[1] = 450.972290039062;
      fVmin[2] = 10.0143241882324;
      fVmax[2] = 228.861190795898;
      fVmin[3] = 0;
      fVmax[3] = 7;
      fVmin[4] = 8.01255989074707;
      fVmax[4] = 972.719665527344;
      fVmin[5] = 10.3086061477661;
      fVmax[5] = 929.568359375;
      fVmin[6] = 3.95599842071533;
      fVmax[6] = 521.006225585938;
      fVmin[7] = -0;
      fVmax[7] = 1068.73571777344;
      fVmin[8] = -2.39974975585938;
      fVmax[8] = 2.39961290359497;
      fVmin[9] = 0;
      fVmax[9] = 4;
      fVmin[10] = 0;
      fVmax[10] = 3;
      fVmin[11] = 0;
      fVmax[11] = 192.143051147461;
      fVmin[12] = 1.36844766139984;
      fVmax[12] = 3.14158463478088;
      fVmin[13] = 2;
      fVmax[13] = 4;
      fVmin[14] = 0;
      fVmax[14] = 0.0999513044953346;
      fVmin[15] = 0;
      fVmax[15] = 0.0999603047966957;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'I';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'F';
      fType[12] = 'I';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCuts() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCuts"
};
   inline double ReadCuts::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
